CREATE DATABASE Do_an_sem_2
GO
USE Do_an_sem_2

GO
CREATE TABLE Categories (
	CateId INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(150) UNIQUE NOT NULL,
	Status BIT DEFAULT 1,
	CreatedAt DATETIME DEFAULT GETDATE()
)

GO
CREATE TABLE Brands (
	BrandId INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(150) UNIQUE NOT NULL,
	ImageUrl VARCHAR(255) NOT NULL,
	Status BIT DEFAULT 1,
	CreatedAt DATETIME DEFAULT GETDATE()
)

GO
CREATE TABLE Products (
	ProId INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(150) NOT NULL,
	ImageUrl VARCHAR(255) NOT NULL,
	Price MONEY NOT NULL,
	Discount MONEY DEFAULT(0),
	CateId INT FOREIGN KEY REFERENCES Categories(CateId),
	BrandId INT FOREIGN KEY REFERENCES Brands(BrandId),
	ShortDescription NTEXT NOT NULL,
	Description NTEXT NOT NULL,
	Quantity INT NOT NULL,
	Status TINYINT DEFAULT 1,
	CreatedAt DATETIME DEFAULT GETDATE()
)

GO
CREATE TABLE Product_images (
	Id INT PRIMARY KEY IDENTITY(1,1),
	ProId INT FOREIGN KEY REFERENCES Products(ProId) NOT NULL,
	ImageUrl VARCHAR(255) NOT NULL
)

GO
CREATE TABLE Accounts (
	AccId INT PRIMARY KEY IDENTITY(1,1),
	AccName NVARCHAR(100) UNIQUE NOT NULL,
	FullName NVARCHAR(150) NOT NULL,
	Email VARCHAR(150) UNIQUE NOT NULL,
	Address NVARCHAR(255) NOT NULL,
	Phone VARCHAR(20) NOT NULL,
	Password VARCHAR(255) NOT NULL,
	Status BIT DEFAULT 1,
	RememberToken VARCHAR(150) NULL,
	CreatedAt DATETIME DEFAULT GETDATE()
)

GO
CREATE TABLE Roles (
	RoleId INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(100) UNIQUE NOT NULL,
	Status BIT DEFAULT 1
)

GO
CREATE TABLE Account_Roles (
	Id INT PRIMARY KEY IDENTITY(1,1),
	AccId INT FOREIGN KEY REFERENCES Accounts(AccId),
	RoleId INT FOREIGN KEY REFERENCES Roles(RoleId)
)

GO
CREATE TABLE Contacts (
	Id INT PRIMARY KEY IDENTITY(1,1),
	AccId INT NULL,
	FullName NVARCHAR(150) NOT NULL,
	Email NVARCHAR(150) NOT NULL,
	Phone VARCHAR(20) NOT NULL,
	Message NTEXT NOT NULL,
	Status BIT DEFAULT 1,
	CreatedAt DATETIME DEFAULT GETDATE()
)

GO
CREATE TABLE Configs (
	Id INT PRIMARY KEY IDENTITY(1,1),
	LogoImage NVARCHAR(250) NOT NULL,
	BannerImage NVARCHAR(250) NOT NULL,
	Address NVARCHAR(250) NOT NULL,
	Map TEXT NOT NULL,
	Phone VARCHAR(20) NOT NULL,
	Email NVARCHAR(150) NOT NULL,
	UpdatedAt DATETIME NULL
)

GO
CREATE TABLE Reviews (
	Id INT PRIMARY KEY IDENTITY(1,1),
	AccId INT FOREIGN KEY REFERENCES Accounts(AccId),
	ProId INT FOREIGN KEY REFERENCES Products(ProId),
	ProductQuality INT NOT NULL,
	ContentRated NTEXT NOT NULL,
	Status BIT DEFAULT 1,
	CreatedAt DATETIME DEFAULT GETDATE()
)

GO
CREATE TABLE Carts (
	CartId INT PRIMARY KEY IDENTITY(1,1),
	AccId INT FOREIGN KEY REFERENCES Accounts(AccId),
	ProId INT FOREIGN KEY REFERENCES Products(ProId),
	Quantity INT NOT NULL,
	TotalPrice MONEY NOT NULL
)

GO
CREATE TABLE Orders (
	OrderId INT PRIMARY KEY IDENTITY(1,1),
	AccId INT FOREIGN KEY REFERENCES Accounts(AccId),
	FullName NVARCHAR(150) NOT NULL,
	Address NVARCHAR(150) NOT NULL,
	Phone VARCHAR(20) NOT NULL,
	Note NTEXT NULL,
	TotalPrice MONEY NOT NULL,
	Status TINYINT DEFAULT 1,
	CreatedAt DATETIME DEFAULT GETDATE(),
	UpdatedAt DATETIME NULL
)

GO
CREATE TABLE OrderDetails (
	Id INT PRIMARY KEY IDENTITY(1,1),
	OrderId INT FOREIGN KEY REFERENCES Orders(OrderId),
	ProId INT FOREIGN KEY REFERENCES Products(ProId),
	Quantity INT NOT NULL,
	Price MONEY NOT NULL
)

GO
CREATE TABLE Blogs (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(255) NOT NULL,
	Title NVARCHAR(255) NOT NULL,
	MainImageUrl VARCHAR(255) NOT NULL,
	Content_1 NTEXT NOT NULL,
	SecondImageUrl VARCHAR(255) NOT NULL,
	Content_2 NTEXT NOT NULL,
	ThirdImageUrl VARCHAR(255) NULL,
	Content_3 NTEXT NULL,
	Status BIT DEFAULT 1,
	CreatedAt DATETIME DEFAULT GETDATE(),
)

GO
CREATE TRIGGER tg_CheckTotalBookOfAuthor
ON Accounts
FOR INSERT
AS
BEGIN
	INSERT Account_Roles VALUES ((SELECT TOP 1 AccId FROM Accounts ORDER BY AccId DESC), 2)
END

GO
INSERT INTO Categories(Name) VALUES ('Men watch'), ('Ladies watches')
GO
INSERT INTO Brands(Name, ImageUrl) VALUES ('Rolex', 'rolex.jpg'), ('Casio', 'casio.jpg')
GO
INSERT INTO Roles(Name) VALUES ('ROLE_ADMIN'), ('ROLE_USER')
GO
INSERT INTO Configs VALUES ('logoImage.png', 'bannerImage.jpg', N'Số 238 Hoàng Quốc Việt, Cầu GIấy, Hà nội', 
'<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4331.764921528694!2d105.71224085080011!3d18.6438196872751!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3139cc46daf9fc6b%3A0x9332dd7c2df8d550!2zTMOqIER1eSDEkGnhur9tLCB0dC4gWHXDom4gQW4sIE5naGkgWHXDom4sIEjDoCBUxKluaCwgVmnhu4d0IE5hbQ!5e1!3m2!1svi!2s!4v1649836718565!5m2!1svi!2s" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>', 'Eiser@gamil.com', '0398888888', '2022-02-02')

select * from Accounts

select * from Account_Roles

