CREATE DATABASE Do_an_sem_2
GO
Use Do_an_sem_2

GO
CREATE TABLE Categories (
	CateId INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(150) UNIQUE NOT NULL,
	Status BIT DEFAULT 1,
	CreatedAt DATETIME DEFAULT GETDATE()
)

GO
CREATE TABLE Brands (
	BrandId INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(150) UNIQUE NOT NULL,
	ImageUrl VARCHAR(255) NOT NULL,
	Status BIT DEFAULT 1,
	CreatedAt DATETIME DEFAULT GETDATE()
)

GO
CREATE TABLE Products (
	ProId INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(150) NOT NULL,
	ImageUrl VARCHAR(255) NOT NULL,
	Price MONEY NOT NULL,
	Discount MONEY DEFAULT(0),
	CateId INT FOREIGN KEY REFERENCES Categories(CateId),
	BrandId INT FOREIGN KEY REFERENCES Brands(BrandId),
	ShortDescription NVARCHAR(255) NOT NULL,
	Description NTEXT NOT NULL,
	Quanity INT NOT NULL, 
	Status BIT DEFAULT 1,
	CreatedAt DATETIME DEFAULT GETDATE()
)

GO
CREATE TABLE Product_images (
	Id INT PRIMARY KEY IDENTITY(1,1),
	ProId INT FOREIGN KEY REFERENCES Products(ProId) NOT NULL,
	ImageUrl VARCHAR(255) NOT NULL
)

GO
CREATE TABLE Accounts (
	AccId INT PRIMARY KEY IDENTITY(1,1),
	AccName NVARCHAR(100) UNIQUE NOT NULL,
	FullName NVARCHAR(150) NOT NULL,
	Email VARCHAR(150) UNIQUE NOT NULL,
	Address NVARCHAR(255) NOT NULL,
	Phone VARCHAR(20) NOT NULL,
	Password VARCHAR(50) NOT NULL,
	Status BIT DEFAULT 1,
	RememberToken VARCHAR(150) NULL,
	CreatedAt DATETIME DEFAULT GETDATE()
)

GO
CREATE TABLE Roles (
	RoleId INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(100) UNIQUE NOT NULL,
	Status BIT DEFAULT 1
)

GO
CREATE TABLE Account_Roles (
	Id INT PRIMARY KEY IDENTITY(1,1),
	AccId INT FOREIGN KEY REFERENCES Accounts(AccId),
	RoleId INT FOREIGN KEY REFERENCES Roles(RoleId)
)

GO
CREATE TABLE Contacts (
	Id INT PRIMARY KEY IDENTITY(1,1),
	AccId INT NULL,
	FullName NVARCHAR(150) NOT NULL,
	Email NVARCHAR(150) NOT NULL,
	Phone VARCHAR(20) NOT NULL,
	Message NTEXT NOT NULL,
	Status BIT DEFAULT 1,
	CreatedAt DATETIME DEFAULT GETDATE()
)

GO
CREATE TABLE Configs (
	LogoImage NVARCHAR(250) NOT NULL,
	BannerImage NVARCHAR(250) NOT NULL,
	Address VARCHAR(250) NOT NULL,
	Map TEXT NOT NULL,
	Email NVARCHAR(150) NOT NULL,
	Phone VARCHAR(20) NOT NULL,
	UpdatedAt DATETIME DEFAULT GETDATE()
)

GO
CREATE TABLE Reviews (
	Id INT PRIMARY KEY IDENTITY(1,1),
	AccId INT FOREIGN KEY REFERENCES Accounts(AccId),
	ProId INT FOREIGN KEY REFERENCES Products(ProId),
	ProductQuality INT NOT NULL,
	ContentRated NTEXT NOT NULL,
	Status BIT DEFAULT 1,
	CreatedAt DATETIME DEFAULT GETDATE()
)

GO
CREATE TABLE Carts (
	CartId INT PRIMARY KEY IDENTITY(1,1),
	AccId INT FOREIGN KEY REFERENCES Accounts(AccId),
	ProId INT FOREIGN KEY REFERENCES Products(ProId),
	Quantity INT NOT NULL,
	TotalPrice MONEY NOT NULL
)

GO
CREATE TABLE Orders (
	OrderId INT PRIMARY KEY IDENTITY(1,1),
	AccId INT FOREIGN KEY REFERENCES Accounts(AccId),
	FullName NVARCHAR(150) NOT NULL,
	Address NVARCHAR(150) NOT NULL,
	Phone VARCHAR(20) NOT NULL,
	Note NTEXT NULL,
	TotalPrice MONEY NOT NULL,
	Status TINYINT DEFAULT 1,
	CreatedAt DATETIME DEFAULT GETDATE(),
	UpdatedAt DATETIME
)

GO
CREATE TABLE OrderDetails (
	Id INT PRIMARY KEY IDENTITY(1,1),
	ProId INT FOREIGN KEY REFERENCES Products(ProId),
	OrderId INT FOREIGN KEY REFERENCES Orders(OrderId),
	Quantity INT NOT NULL,
	Price MONEY NOT NULL
)

GO
CREATE TABLE Blogs (
	Id INT PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(255) NOT NULL,
	Title NVARCHAR(255) NOT NULL,
	MainImageUrl VARCHAR(255) NOT NULL,
	Content_1 NTEXT NOT NULL,
	SecondImageUrl VARCHAR(255) NOT NULL,
	Content_2 NTEXT NOT NULL,
	ThirdImageUrl VARCHAR(255) NULL,
	Content_3 NTEXT NULL,
	Status INT DEFAULT 1,
	CreatedAt DATETIME DEFAULT GETDATE(),
)
